### ISSUE TITLE
Safari, Chrome, Opera miss the icons

### ISSUE THREAD

**Issue by niqt** [Lattyware/elm-fontawesome#10]
In my application i use these icons but are visible only if i using Firefox. Do i have done some mistakes or is a bug? I run the browser on OSX.

**Comment by Lattyware** [comment]
Sorry for the very late response, did you include the styles in the page as per [the readme](https://github.com/Lattyware/elm-fontawesome#required-css=)? That may cause icons to present weirdly when missing. Otherwise, I'm not sure what would cause that.

**Comment by Lattyware** [comment]
Closing this as I'm assuming this is missing styles, as I can't reproduce, please open a new issue if you run into this again.
