### ISSUE TITLE
Please update the icons :)

### ISSUE THREAD

**Issue by gacallea** [Lattyware/elm-fontawesome#11]
Hi @Lattyware,

thank you for this amazing Elm package. By far, the best Font Awesome implementation. I suppose this issue https://github.com/Lattyware/elm-fontawesome/issues/7 would automate what I'm about to request? Not sure, so here I am:

Please update the package to include newer icons since release. I'm using this package and need to make a CSS audio player for my site, and some icons are missing (i.e: https://fontawesome.com/icons/shuffle?s=solid and https://fontawesome.com/icons/repeat?s=solid)

Looking forward to updates (generally speaking, not with my specific request) and improvements of this great package :)

Best,

**Comment by Lattyware** [comment]
I've published [the update supporting FontAwesome 6.x](https://package.elm-lang.org/packages/lattyware/elm-fontawesome/6.0.0/), it's got [some pretty significant differences](https://github.com/Lattyware/elm-fontawesome/releases/tag/6.0.0).

**Comment by gacallea** [comment]
Thank you so much! I've just noticed this, sorry for the late reply :)
