### ISSUE TITLE
Problem building dependencies

### ISSUE THREAD

**Issue by CharlonTank** [Lattyware/elm-fontawesome#15]
Hello, I get this error:

-------------------------------

PROBLEM BUILDING DEPENDENCIES - I ran into a compilation error when trying to build the following package:

    lattyware/elm-fontawesome 7.0.0

This probably means it has package constraints that are too wide. It may be
possible to tweak your elm.json to avoid the root problem as a stopgap. Head
over to https://elm-lang.org/community to get help figuring out how to take this
path!

Note: To help with the root problem, please report this to the package author
along with the following information:

    elm/core 1.0.5
    elm/html 1.0.0
    elm/svg 1.0.1

If you want to help out even more, try building the package locally. That should
give you much more specific information about why this package is failing to
build, which will in turn make it easier for the package author to fix it!

---------

🙏

**Comment by CharlonTank** [comment]
Thank you @leojpod, @Lattyware, what do you think about this?
🙏

**Comment by Lattyware** [comment]
I can't reproduce any problem here, it builds fine for me in my test cases, but I've made the change in the generator as I can't imagine any issue arising (no one is going to be stuck on an old version of core after so long).

**Comment by Lattyware** [comment]
Reopened as apparently [the issue still exists](https://github.com/Lattyware/elm-fontawesome/pull/16#issuecomment-2119566981 ).

**Comment by CharlonTank** [comment]
Thank you for reopening the issue, basically, I use VSCode and I always get this error:

<img width="916" alt="image" src="https://github.com/Lattyware/elm-fontawesome/assets/4601603/ec82a356-a977-44b2-a4b1-6ef13f7bc5f7">

**Comment by Lattyware** [comment]
OK, now published, please give [7.1.2](https://package.elm-lang.org/packages/lattyware/elm-fontawesome/7.1.2/) a try and see if it works for you, it correctly installed and worked for [the example](https://github.com/Lattyware/elm-fontawesome-example), so if not I suspect it's something with your environment.
