### ISSUE TITLE
Please publish the latest version on elm packages

### ISSUE THREAD

**Issue by Clindbergh** [Lattyware/elm-fontawesome#9]
The master branch version uses Fontawesome v5.12 but the released version on elm packages is older. Please consider publishing the latest version on the master branch.

Potentially this would also be an opportunity to [upgrade to v5.14](https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md).

Thank you for the creation and publising of this library.

**Comment by Clindbergh** [comment]
[This github action could be helpful to avoid this issues in future while also reducing your workload](https://github.com/dillonkearns/elm-publish-action) (found via [elm-radio](https://elm-radio.com/episode/publishing-packages/)).

**Comment by Lattyware** [comment]
There is an automated build and publish, it is just run on Travis and there was apparently an issue with the build on Node 10. I'm bumping the version and seeing if it will build through now.

I'd like to port it over to GitHub Actions from Travis, but it's a reasonably complex workflow and I can't dedicate the time to it right now. I'd be happy to accept a pull request (although I think it would probably be awkward to do as a PR).

**Comment by Lattyware** [comment]
Published as [5.0.0](https://package.elm-lang.org/packages/lattyware/elm-fontawesome/5.0.0/) (there was a removed icon forcing the major version change).

**Comment by Clindbergh** [comment]
Thanks!
